version: "3.9"

services:

  flask_app:
    build: .
    command: python main.py
    ports:
      - "5001:5000"
    depends_on:
      - rabbitmq

  celery_worker:
    build: .
    command: celery -A celery_app.celery_app worker -l info
    depends_on:
      - rabbitmq

  celery_beat:
    build: .
    command: celery -A celery_app.celery_app beat -l info
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"